image: golang:1.16

variables:
  REPO_NAME: github.com/holykol/literotigo
  GOPROXY: direct

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build

test:
  stage: test
  script:
    - go fmt ./...
    - go vet ./...
    - go test -race -coverprofile=cov.out ./...
    - go tool cover -html=cov.out -o coverage.html
  artifacts:
    paths:
      - coverage.html


build:
  stage: build
  script:
    - go build -o $CI_PROJECT_DIR/literotigo
  artifacts:
    paths:
      - literotigo
